name: Tests

on:
  push:
    branches: 
      - main

jobs:
  test-pip:
    name: Run tests (with pip)

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - run: git fetch --prune --unshallow --tags

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Python environment
      run: |
        python3 -m pip install --upgrade build pip setuptools
        pip3 install numpy numba scipy matplotlib tqdm pytest matplotlib-label-lines

    - name: Install OpenTerrace
      run: |
        python3 -m build
        pip3 freeze

    - name: Run tests
      run: |
        python3 -m pytest
