name: Tests

on:
  push:
    branches: 
      - main

jobs:
  test-pip:
    name: Run tests (with pip)

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - run: git fetch --prune --unshallow --tags

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Python environment
      run: |
        python -m pip install --upgrade build pip setuptools
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Install OpenTerrace
      run: |
        python -m build
        pip freeze

    - name: Run tests
      run: |
        python3 -m pytest
